---
stages:
  - test
  - deploy

simple-test:
  stage: test
  image: alpine:latest
  script:
    - echo "CI/CD pipeline is working!"
    - echo "Project setup successful!"
  only:
    - pushes
    - merge_requests

pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir -p public
    - ls -la  # 디버깅용: 현재 디렉토리 구조 확인
    - cp -r index.html public/ || echo "No index.html found"
    - mkdir -p public/js
    - cp -r js/*.js public/js/ || echo "No JS files found"
    - mkdir -p public/assets
    - cp -r assets/* public/assets/ || echo "No assets found"
    - echo "Game files deployed to Pages!"
  artifacts:
    paths:
      - public
  only:
    - main