stages:
  - lint

eslint:
  stage: lint
  image: node:latest
  script:
    - npm install eslint
    - npx eslint .
  only:
    - pushes
    - merge_requests

yamllint:
  stage: lint
  image: python:alpine
  before_script:
    - pip install yamllint
  script:
    - yamllint .
  only:
    - pushes
    - merge_requests