---
stages:
  - test
  - deploy

simple-test:
  stage: test
  image: alpine:latest
  script:
    - echo "CI/CD pipeline is working!"
    - echo "Project setup successful!"
  only:
    - pushes
    - merge_requests

pages:
  stage: deploy
  image: alpine:latest
  script:
    - mkdir -p public
    - ls -la
    # index.html 복사
    - cp -r index.html public/ || echo "No index.html found"
    # JS 파일 복사 (js 폴더 구조 유지)
    - mkdir -p public/js
    - cp -r js/ public/ || echo "No JS folder found"
    # assets 복사 (존재하는 경우)
    - mkdir -p public/assets
    - cp -r assets/ public/ || echo "No assets folder found"
    # CDN에서 Phaser 라이브러리 직접 다운로드
    - apk add --no-cache curl
    - curl -o public/phaser.js https://cdn.jsdelivr.net/npm/phaser@3.88.2/dist/phaser.js || echo "Failed to download Phaser"
    - echo "Game files deployed to Pages!"
  artifacts:
    paths:
      - public
  only:
    - main