---
stages:
  - test

# 간단한 테스트 작업만 설정
simple-test:
  stage: test
  image: alpine:latest
  script:
    - echo "CI/CD pipeline is working!"
    - echo "Project setup successful!"
  only:
    - pushes
    - merge_requests